### ISSUE TITLE
show running-config displays ip route  route->nexthop instead of expected route

### ISSUE THREAD

**Issue by andrnils** [clicon/rost#10]
show running-config displays 
'ip route route->nexthop'
instead of 
'ip route x.y.z.w a.b.c.d'

diff --git a/frontend/ios/ios.d2t b/frontend/ios/ios.d2t
index 8939955..d9ebf5e 100644
--- a/frontend/ios/ios.d2t
+++ b/frontend/ios/ios.d2t
@@ -43,7 +43,7 @@
 @IF($router.bgp->as)
 @INCLUDE("${ROST_PLUGIN_DIR}/ios-router-bgp.d2t")
 @END
-@EACH($ipv4.route.static[], $rt, "ip route $rt->prefix route->nexthop $rt->distance\n")
+@EACH($ipv4.route.static[], $rt, "ip route $rt->prefix $rt->nexthop $rt->distance\n")
 @EACH($ipv4.route.static.null[], $rt)
 ip route $rt->prefix @IF($rt->reject ? "reject" : "blackhole") $rt->distance\n
 @END

Might be the solution.

**Comment by bholmgren** [comment]
This is corrected along with a bunch of other formatting issues in the last commit
